language: cpp
cache: ccache
os: linux
matrix:
  include:
    - name: "Test Suite"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      install:
        - export CC='ccache gcc-4.9' CXX='ccache g++-4.9' JOBS=2
        - ./configure
        - make -j2 V=
      script:
        - PARALLEL_ARGS='--flaky-tests=skip' make -j1 test
