language: cpp
cache: ccache
os: linux

env:
  global:
    - REPO_NAME="nodejs-mobile"
    - ARTIFACTS_ROOT_DIR=$REPO_NAME
    - ARTIFACTS_DIR=$ARTIFACTS_ROOT_DIR/$REPO_NAME/$TRAVIS_BRANCH/$TRAVIS_JOB_NUMBER

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - curl https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -o ndk.zip
  - unzip -qq ndk.zip -d $HOME
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
  - |
    case $ARCH in
      arm)
        export TARGET_ARCH="arm"
        ;;
      x86)
        export TARGET_ARCH="x86"
        ;;
      x86_64)
        export TARGET_ARCH="x86_64"
        ;;
      *)
        export TARGET_ARCH="arm64"
        ;;
    esac

install:
  - ./tools/android_build.sh $ANDROID_NDK_HOME $TARGET_ARCH

script: skip

before_deploy:
  - mkdir -p $ARTIFACTS_DIR
  - cp -r out_android $ARTIFACTS_DIR
  - cp -r out/Release/lib.target $ARTIFACTS_DIR

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_Bucket
  skip_cleanup: true
  local_dir: $ARTIFACTS_ROOT_DIR
  on:
    all_branches: true
