language: cpp
cache: ccache
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - curl https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -o ndk.zip
  - unzip ndk.zip -d $HOME
  - ls $HOME
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
  - ls $ANDROID_NDK_HOME
  - |
    case $ARCH in
      arm)
        export TARGET_ARCH="arm"
        ;;
      x86)
        export TARGET_ARCH="x86"
        ;;
      x86_64)
        export TARGET_ARCH="x86_64"
        ;;
      *)
        export TARGET_ARCH="arm64"
        ;;
    esac

install:
  - ./tools/android_build.sh $ANDROID_NDK_HOME $TARGET_ARCH

script: skip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_Bucket
  skip_cleanup: true
  local_dir: out_android
